spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    url: jdbc:postgresql://localhost:5454/postgres
    password: 1254
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: user-db
server:
  port: 8081
  error:
    include-message: always
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

